### ISSUE TITLE
[typescript-transfer] Рефакторинг компонента pages-tree

### ISSUE THREAD

**Issue by ValeriyaKa** [textify-bundle/textify-frontend#7]
- [x] сопоставить компонент с дизайном
- [x] проверить scss формат
- [x] проверить что стили в scss в БЭМ формате
- [x] перенести типизацию пропсов в TypeScript формат с понятными названиями
- [ ] написать тесты для компонентов

**Comment by poplopok** [comment]
Все хорошо
