### ISSUE TITLE
[typescript-transfer] Рефакторинг компонента project-card

### ISSUE THREAD

**Issue by ValeriyaKa** [textify-bundle/textify-frontend#8]
- [x] сопоставить компонент с дизайном
- [x] проверить scss формат
- [x] проверить что стили в scss в БЭМ формате
- [x] перенести типизацию пропсов в TypeScript формат с понятными названиями
- [x] написать тесты для компонентов

**Comment by bassceo** [comment]
Также добавил доку
![Image](https://github.com/user-attachments/assets/beb74e3a-e9fe-45c0-bccd-c7b2b0ed202a)
